language: R
sudo: false
cache:
  packages: true
  directories:
  - _bookdown_files
  - $HOME/.npm

pandoc_version: 2.1.1

before_install:
- sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
- sudo apt-get --yes --force-yes update -qq
- sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev

script:
- Rscript -e 'bookdown::render_book("index.Rmd")'

after_success:
- nvm install stable
- npm install netlify-cli -g

deploy:
  provider: script
  script: netlify deploy --prod --dir _book
  skip_cleanup: true
